apiVersion: 1

datasources:
  - name: parsedmarc-aggregate
    type: elasticsearch
    uid: parsedmarc-aggregate
    url: http://elasticsearch:9200
    isDefault: true
    jsonData:
      esVersion: "8.0.0"
      timeField: date_range
      maxConcurrentShardRequests: 5
    database: dmarc_aggregate*

  - name: parsedmarc-forensic
    type: elasticsearch
    uid: parsedmarc-forensic
    url: http://elasticsearch:9200
    jsonData:
      esVersion: "8.0.0"
      timeField: date_range
      maxConcurrentShardRequests: 5
    database: dmarc_forensic*
